### PR TITLE
Update itertools, bump version

### PR DESCRIPTION
**Pull request by alexbool**

### CODE REVIEW

**Comment by bluss** [comment]
Hi, this doesn't need a version bump. I don't see it, at least.

**Comment by alexbool** [comment]
Agreed & updated.

**Comment by bluss** [comment]
Thanks

**Comment by alexbool** [comment]
I'd also ask you to publish this release.

**Comment by bluss** [comment]
Ok, I'll ask you belatedly then, what's the motivation of this pr? It's a dev dependency.

**Pull request merged**
